[window]
decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 12.0
